#!/command/with-contenv bash

source /assets/functions/01-dbbackup-compat
prepare_service single
PROCESS_NAME="db-backup"
output_off

setup_mode
db_backup_container_init
create_schedulers backup

liftoff
